CREATE TABLE IF NOT EXISTS PROYECTO (
	ID INT AUTO_INCREMENT NOT NULL,
    NOMBRE VARCHAR(30) NOT NULL,
    DESCRIPCION VARCHAR(255),
    IMAGEN VARCHAR(255),
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS LIBRO (
	ID INT AUTO_INCREMENT NOT NULL,
    NOMBRE VARCHAR(30) NOT NULL,
    DESCRIPCION VARCHAR(255),
    GENERO VARCHAR(40),
    IMAGEN VARCHAR(255),
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS PERSONAJE (
	ID INT AUTO_INCREMENT NOT NULL,
    NOMBRE VARCHAR(20) NOT NULL,
    APELLIDO1 VARCHAR(20),
    APELLIDO2 VARCHAR(20),
    EDAD INT,
    DESCRIPCION VARCHAR(255),  
    IMAGEN VARCHAR(255),
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS LOCALIDAD (
	ID INT AUTO_INCREMENT NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    DESCRIPCION TEXT,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS CAPITULO (
	ID INT AUTO_INCREMENT NOT NULL,
    IDLIBRO INT NOT NULL,
    NOMBRE VARCHAR(20),
    NUMERO INT,
    DESCRIPCION TEXT,
    PRIMARY KEY (ID),
    FOREIGN KEY (IDLIBRO) REFERENCES LIBRO (ID)
);

CREATE TABLE IF NOT EXISTS ESCENA (
	ID INT AUTO_INCREMENT NOT NULL,
    IDLOCALIDAD INT NOT NULL,
    IDCAPITULO INT NOT NULL,
	NOMBRE VARCHAR(20),
    DESCRIPCION TEXT,
    ORDEN INT,
    PRIMARY KEY (ID),
    FOREIGN KEY (IDLOCALIDAD) REFERENCES LOCALIDAD (ID),
    FOREIGN KEY (IDCAPITULO) REFERENCES CAPITULO (ID)
);

CREATE TABLE IF NOT EXISTS ESCENA_PERSONAJE (
	IDESCENA INT NOT NULL,
    IDPERSONAJE INT NOT NULL,
    PRIMARY KEY (IDESCENA, IDPERSONAJE),
    FOREIGN KEY (IDESCENA) REFERENCES ESCENA (ID),
    FOREIGN KEY (IDPERSONAJE) REFERENCES PERSONAJE (ID)
);

CREATE TABLE IF NOT EXISTS LIBRO_PERSONAJE (
	IDLIBRO INT NOT NULL,
    IDPERSONAJE INT NOT NULL,
    PRIMARY KEY (IDLIBRO, IDPERSONAJE),
    FOREIGN KEY (IDLIBRO) REFERENCES LIBRO(ID),
    FOREIGN KEY (IDPERSONAJE) REFERENCES PERSONAJE (ID)
);

CREATE TABLE IF NOT EXISTS PROYECTO_LIBRO (
	IDPROYECTO INT NOT NULL,
    IDLIBRO INT NOT NULL,
    PRIMARY KEY (IDPROYECTO, IDLIBRO),
    FOREIGN KEY (IDPROYECTO) REFERENCES PROYECTO (ID),
    FOREIGN KEY (IDLIBRO) REFERENCES LIBRO (ID)
);