package model;
// Generated 14-may-2020 19:33:07 by Hibernate Tools 5.4.14.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Escena generated by hbm2java
 */
public class Escena implements java.io.Serializable {

	private static final long serialVersionUID = -2108701616098456638L;
	
	private Integer id;
	private Capitulo capitulo;
	private Localidad localidad;
	private String nombre;
	private String descripcion;
	private Set<Personaje> personajes = new HashSet<Personaje>(0);

	public Escena() {
	}

	public Escena(Capitulo capitulo, Localidad localidad) {
		this.capitulo = capitulo;
		this.localidad = localidad;
	}

	public Escena(Capitulo capitulo, Localidad localidad, String nombre, String descripcion, Set<Personaje> personajes) {
		this.capitulo = capitulo;
		this.localidad = localidad;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.personajes = personajes;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Capitulo getCapitulo() {
		return this.capitulo;
	}

	public void setCapitulo(Capitulo capitulo) {
		this.capitulo = capitulo;
	}

	public Localidad getLocalidad() {
		return this.localidad;
	}

	public void setLocalidad(Localidad localidad) {
		this.localidad = localidad;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set<Personaje> getPersonajes() {
		return this.personajes;
	}

	public void setPersonajes(Set<Personaje> personajes) {
		this.personajes = personajes;
	}

}
