package model;
// Generated 23-may-2020 19:25:06 by Hibernate Tools 5.4.14.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Escena generated by hbm2java
 */
public class Escena implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2617893976012216846L;
	private Integer id;
	private Capitulo capitulo;
	private Localidad localidad;
	private String nombre;
	private String descripcion;
	private Integer orden;
	private Set<Personaje> personajes = new HashSet<Personaje>(0);

	public Escena() {
	}

	public Escena(Capitulo capitulo, Localidad localidad) {
		this.capitulo = capitulo;
		this.localidad = localidad;
	}

	public Escena(Capitulo capitulo, Localidad localidad, String nombre, String descripcion, Integer orden,
			Set<Personaje> personajes) {
		this.capitulo = capitulo;
		this.localidad = localidad;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.orden = orden;
		this.personajes = personajes;
	}

	public Escena(Capitulo chapter, Localidad localidad, String name, String description, Set<Personaje> characters) {
		this.capitulo = chapter;
		this.localidad = localidad;
		this.nombre = name;
		this.descripcion = description;
		this.personajes = characters;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Capitulo getCapitulo() {
		return this.capitulo;
	}

	public void setCapitulo(Capitulo capitulo) {
		this.capitulo = capitulo;
	}

	public Localidad getLocalidad() {
		return this.localidad;
	}

	public void setLocalidad(Localidad localidad) {
		this.localidad = localidad;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Integer getOrden() {
		return this.orden;
	}

	public void setOrden(Integer orden) {
		this.orden = orden;
	}

	public Set<Personaje> getPersonajes() {
		return this.personajes;
	}

	public void setPersonajes(Set<Personaje> personajes) {
		this.personajes = personajes;
	}
	
	@Override
	public String toString() {
		return this.getNombre();
	}

}
