package model;
// Generated 14-may-2020 19:33:07 by Hibernate Tools 5.4.14.Final

import java.util.HashSet;
import java.util.Set;
import java.util.TreeSet;

import org.hibernate.Hibernate;

/**
 * Libro generated by hbm2java
 */
public class Libro implements java.io.Serializable {

	private static final long serialVersionUID = 1064183966633645117L;
	
	private Integer id;
	private String nombre;
	private String descripcion;
	private String genero;
	private String imagen;
	private Set<Personaje> personajes = new HashSet<Personaje>(0);
	private Set<Capitulo> capitulos = new TreeSet<Capitulo>();
	private Set<Proyecto> proyectos = new HashSet<Proyecto>(0);

	public Libro() {
	}

	public Libro(String nombre) {
		this.nombre = nombre;
	}
	
	public Libro(String nombre, String descripcion, String genero, String imagen, Set<Personaje> personajes, Set<Proyecto> proyectos) {
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.genero = genero;
		this.imagen = imagen;
		this.personajes = personajes;
		this.proyectos = proyectos;
	}

	public Libro(String nombre, String descripcion, String genero, String imagen, Set<Personaje> personajes, Set<Capitulo> capitulos,
			Set<Proyecto> proyectos) {
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.genero = genero;
		this.imagen = imagen;
		this.personajes = personajes;
		this.capitulos = capitulos;
		this.proyectos = proyectos;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getGenero() {
		return this.genero;
	}

	public void setGenero(String genero) {
		this.genero = genero;
	}

	public String getImagen() {
		return this.imagen;
	}

	public void setImagen(String imagen) {
		this.imagen = imagen;
	}

	public Set<Personaje> getPersonajes() {
		
		for (Personaje p : personajes) {
			Hibernate.initialize(p);
		}
		
		return this.personajes;
	}

	public void setPersonajes(Set<Personaje> personajes) {
		this.personajes = personajes;
	}

	public Set<Capitulo> getCapitulos() {
		return this.capitulos;
	}

	public void setCapitulos(Set<Capitulo> capitulos) {
		this.capitulos = capitulos;
	}

	public Set<Proyecto> getProyectos() {
		
		for (Proyecto p : proyectos) {
			Hibernate.initialize(p);
		}
		
		return this.proyectos;
	}

	public void setProyectos(Set<Proyecto> proyectos) {
		this.proyectos = proyectos;
	}

	@Override
	public String toString() {
		return getNombre();
	}
	
	

}
