package model;
// Generated 23-may-2020 19:25:06 by Hibernate Tools 5.4.14.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Libro generated by hbm2java
 */
public class Libro implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5360746636630053857L;
	private Integer id;
	private String nombre;
	private String descripcion;
	private String genero;
	private String imagen;
	private Set<Capitulo> capitulos = new HashSet<Capitulo>(0);
	private Set<Proyecto> proyectos = new HashSet<Proyecto>(0);
	private Set<Personaje> personajes = new HashSet<Personaje>(0);

	public Libro() {
	}

	public Libro(String nombre) {
		this.nombre = nombre;
	}

	public Libro(String nombre, String descripcion, String genero, String imagen, Set<Capitulo> capitulos, Set<Proyecto> proyectos,
			Set<Personaje> personajes) {
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.genero = genero;
		this.imagen = imagen;
		this.capitulos = capitulos;
		this.proyectos = proyectos;
		this.personajes = personajes;
	}

	public Libro(String name, String description, String genre, String imagePath, Set<Personaje> characters,
			Set<Proyecto> projects) {
		this.nombre = name;
		this.descripcion = description;
		this.genero = genre;
		this.imagen = imagePath;
		this.proyectos = projects;
		this.personajes = characters;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getGenero() {
		return this.genero;
	}

	public void setGenero(String genero) {
		this.genero = genero;
	}

	public String getImagen() {
		return this.imagen;
	}

	public void setImagen(String imagen) {
		this.imagen = imagen;
	}

	public Set<Capitulo> getCapitulos() {
		return this.capitulos;
	}

	public void setCapitulos(Set<Capitulo> capitulos) {
		this.capitulos = capitulos;
	}

	public Set<Proyecto> getProyectos() {
		return this.proyectos;
	}

	public void setProyectos(Set<Proyecto> proyectos) {
		this.proyectos = proyectos;
	}

	public Set<Personaje> getPersonajes() {
		return this.personajes;
	}

	public void setPersonajes(Set<Personaje> personajes) {
		this.personajes = personajes;
	}

	@Override
	public String toString() {
		return this.getNombre();
	}
	
	

}
