package model;
// Generated 14-may-2020 19:33:07 by Hibernate Tools 5.4.14.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Libro generated by hbm2java
 */
public class Libro implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private String descripcion;
	private String genero;
	private String imagen;
	private Set personajes = new HashSet(0);
	private Set capitulos = new HashSet(0);
	private Set proyectos = new HashSet(0);

	public Libro() {
	}

	public Libro(String nombre) {
		this.nombre = nombre;
	}

	public Libro(String nombre, String descripcion, String genero, String imagen, Set personajes, Set capitulos,
			Set proyectos) {
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.genero = genero;
		this.imagen = imagen;
		this.personajes = personajes;
		this.capitulos = capitulos;
		this.proyectos = proyectos;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getGenero() {
		return this.genero;
	}

	public void setGenero(String genero) {
		this.genero = genero;
	}

	public String getImagen() {
		return this.imagen;
	}

	public void setImagen(String imagen) {
		this.imagen = imagen;
	}

	public Set getPersonajes() {
		return this.personajes;
	}

	public void setPersonajes(Set personajes) {
		this.personajes = personajes;
	}

	public Set getCapitulos() {
		return this.capitulos;
	}

	public void setCapitulos(Set capitulos) {
		this.capitulos = capitulos;
	}

	public Set getProyectos() {
		return this.proyectos;
	}

	public void setProyectos(Set proyectos) {
		this.proyectos = proyectos;
	}

}
