package model;
// Generated 14-may-2020 19:33:07 by Hibernate Tools 5.4.14.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Proyecto generated by hbm2java
 */
public class Proyecto implements java.io.Serializable {

	private static final long serialVersionUID = -7291729140826692519L;
	
	private Integer id;
	private String nombre;
	private String descripcion;
	private String imagen;
	private Set<Libro> libros = new HashSet<Libro>(0);

	public Proyecto() {
	}

	public Proyecto(String nombre) {
		this.nombre = nombre;
	}

	public Proyecto(String nombre, String descripcion, String imagen, Set<Libro> libros) {
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.imagen = imagen;
		this.libros = libros;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getImagen() {
		return this.imagen;
	}

	public void setImagen(String imagen) {
		this.imagen = imagen;
	}

	public Set<Libro> getLibros() {
		return this.libros;
	}

	public void setLibros(Set<Libro> libros) {
		this.libros = libros;
	}

	@Override
	public String toString() {
		return getNombre();
	}
	
	

}
